// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSimFT.EFModels;

public partial class AircraftProperty
{
    public string PropertyId { get; set; }

    public string Unit { get; set; }

    public string PropertyType { get; set; }

    public string PropertyName { get; set; }

    public string Description { get; set; }
}