// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSimFT.EFModels;

public partial class AircraftEngine
{
    public int EngineId { get; set; }

    public string EngineName { get; set; }

    public string EngineFamily { get; set; }

    public int? ManufacturerId { get; set; }

    public string Guid { get; set; }
}