// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSimFT.EFModels;

public partial class AircraftManufacturer
{
    public string ManufacturerName { get; set; }

    public string ManufacturerCountry { get; set; }

    public string ManufacturerGuid { get; set; }

    public virtual ICollection<AircraftModel> AircraftModels { get; set; } = new List<AircraftModel>();

    public virtual ICollection<AircraftType> AircraftTypes { get; set; } = new List<AircraftType>();
}