// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSimFT.EFModels;

public partial class Region
{
    public int RegionId { get; set; }

    public string RegionCode { get; set; }

    public string LocalCode { get; set; }

    public string RegionName { get; set; }

    public string Continent { get; set; }

    public string IsoCountry { get; set; }

    public string WikipediaLink { get; set; }

    public string Keywords { get; set; }

    public virtual ICollection<Airport> Airports { get; set; } = new List<Airport>();
}