// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSimFT.EFModels;

public partial class XpAircraft
{
    public int AcId { get; set; }

    public string AcGuid { get; set; }

    public string AcName { get; set; }

    public string AcType { get; set; }

    public string FuelType { get; set; }

    public int MaxTakeoffWeight { get; set; }

    public int MaxLandingWeight { get; set; }

    public int EmptyOpWeight { get; set; }

    public int MaxPass { get; set; }

    public int MaxCruise { get; set; }

    public int LongRangeCruise { get; set; }

    public int FinalApproachSpeed { get; set; }

    public int MinTakeoffDist { get; set; }

    public int MinLandingDist { get; set; }

    public int ServiceRange { get; set; }

    public int ServiceCeiling { get; set; }

    public int RotateSpeed { get; set; }

    public int LandingSpeed { get; set; }

    public int StallSpeed { get; set; }
}