// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSimFT.EFModels;

public partial class XpFlightPlan
{
    public int FpId { get; set; }

    public DateTime DateCreated { get; set; }

    public int AircraftId { get; set; }

    public string DepartIdent { get; set; }

    public string DepartAirport { get; set; }

    public string DepartCity { get; set; }

    public string DepartRegion { get; set; }

    public string DepartCountry { get; set; }

    public string DestIdent { get; set; }

    public string DestAirport { get; set; }

    public string DestCity { get; set; }

    public string DestRegion { get; set; }

    public string DestCountry { get; set; }

    public int? DistanceNm { get; set; }

    public TimeSpan? EstFlightTime { get; set; }

    public DateTime? DateFlown { get; set; }

    public bool PlaneCrash { get; set; }

    public virtual XpAircraft Aircraft { get; set; } = null!;
}